### ISSUE TITLE
テキスト入力の実装方法検討

### ISSUE THREAD

**Issue by hayato0309** [Recursion-Group-S/watashi#3]
要件
・指定のfont-familyで文字入力ができる
・文字を入力している間もfont-familyで指定した文字が表示されるようにする（入力中の文字は隠してスタイリングされた文字がリアクティブに表示される）

**Comment by dancing-amigo** [comment]
Issue作成ありがとうございます。
htmlファイルでちょっとkonvaを使ってみたのですが上記の要件すべて達成出来ました。
konvaのTextオブジェクトにfontFamilyやfontSize、fill(color)などのプロパティがあるのでそれを変更するだけでできます。

キャンバス内に座標を指定してあたらしいテキストエリアを作成することもでき、サイズの変更、回転なども自由にできました。全部Konvaの機能を使用します

**Comment by hayato0309** [comment]
@takeshi8989 
早いですね！
ありがとうございます🙇‍♂️
ちなみに手書き風のいい感じのfont-familyありますかね？
もしあったら僕が別に調べようと思っていたfabric.jsは使う必要がなくなりそうで！

**Comment by dancing-amigo** [comment]
font-familyはKonva上で
https://fontfaceobserver.com
がおすすめされているので、google fontとかで探せばいいのがあるかなーと思います！
まだちゃんとは読んでないんですけど、webfontloaderでfontをloadして使用する感じですね！
https://konvajs.org/docs/sandbox/Custom_Font.html

**Comment by hayato0309** [comment]
@takeshi8989 
ありがとうございます！
手書き風フォントもkonvaで実現できそうですね！
（ということでfabric.jsは一旦置いておきます）
