### ISSUE TITLE
loadingアニメーション作成

### ISSUE THREAD

**Issue by hayato0309** [Recursion-Group-S/watashi#30]
画像やIconをfetchするときにLoadingアニメーションを表示する

**Comment by satojin219** [comment]
useQueryやuseSWRなどのライブラリでフェッチすることでエラー、ローディング時のレンダリングを出し分ける事ができそうです！

**Comment by hayato0309** [comment]
もし違ってたら申し訳ないのですが、
Map作成ページにてリロードした時にトップページ（http://localhost:3000/）に戻るように変更しましたか？

今まではMap作成ページでリロードすると「loading」の文字が出てきて、再度Map作成ページが表示されるようになっていたと思うのですが、今はトップページに行くようになっています。
