### ISSUE TITLE
ComponentやMapを画像として保存する

### ISSUE THREAD

**Issue by hayato0309** [Recursion-Group-S/watashi#33]
ComponentやMapを画像として保存する

**Comment by dancing-amigo** [comment]
canvas.toDataURL({ left: 100, top: 100, width: 100, height: 100 })

**Comment by hayato0309** [comment]
@takeshi8989 
ありがとうございます！
ということは、
今Canvas部分は<div>で作っていますが<canvas>に変える必要があるってことですかね？🤔

**Comment by dancing-amigo** [comment]
@hayato0309 
上のやつはメモ程度なのでまだ実装できるか分かりませんが、Konvaがcanvasを使用しているのでこのままで画像化できると思います！
