### ISSUE TITLE
Clear AllボタンがTextに効いていない

### ISSUE THREAD

**Issue by hayato0309** [Recursion-Group-S/watashi#47]
Icon, Image, DrawingはClear Allで消えるが、Textだけ消えない

**Comment by dancing-amigo** [comment]
現在はTextだけ別の配列で管理しているのでそうなります！
IconやImageと同じようにItemとして一つの配列で管理するようにしますね

**Comment by hayato0309** [comment]
実装してないだけでしたね！
失礼しました！

2022年10月28日(金) 1:50 TAKESHI ***@***.***>:
