### ISSUE TITLE
galleryページのUI変更

### ISSUE THREAD

**Issue by hayato0309** [Recursion-Group-S/watashi#56]
MapをホバーしたらEditボタンとViewボタンを表示

**Comment by satojin219** [comment]
mapタイトルや作成者のアイコンを表示できると良さそうです！あとページネーションも実装したいですね

**Comment by hayato0309** [comment]
@satojin219 
タイトルは別ブランチ（タイトル保存機能）のところで実装しています！
作業範囲が大きくなりそうだったのでアイコンやページネーションは別のIssue切ろうと思っています！
