### ISSUE TITLE
Galleryのページネーション実装

### ISSUE THREAD

**Issue by hayato0309** [Recursion-Group-S/watashi#69]

**Comment by dancing-amigo** [comment]
https://user-images.githubusercontent.com/109770597/199624785-5278afb0-080f-457b-9393-8f28dbdb400d.mp4

**Comment by dancing-amigo** [comment]
1. URLを変更しないページネーション
2. Mapが4つ以下の時のスタイル設定
3. Mapの並び順が決まってない？createdAtでソートしたい

**Comment by hayato0309** [comment]
@takeshi8989 
1.  その実装でOKです！
2. 動画でいう4ページ目を言ってますか？もしMapが左に寄っていることを言っているのであれば、僕はそんなに問題じゃないかなとも思っています！
3. 確かにソートしたいですね（FriendsのMapは気づかないですが、自分のMapだと作った順じゃないと確かに気になります）

よろしくお願いします！

**Comment by dancing-amigo** [comment]
2. 個人的には4ページ目の高さの違い(pageボタンやcreateボタンが上にくる)が気になりなるのですが、このままで大丈夫ですかね？
3. そうですよね！ソートは別ブランチでやります

あと、Friends Galleryも同じブランチでやってしまいます。ページネーションが必要なので

**Comment by hayato0309** [comment]
@takeshi8989 
2. 確かに気になり始めました！Map8個を含むエレメントに高さ持たせましょう！
3. わかりました！PR作成時に「ソートはやってないよ」ってメモ残していただけると！

Friends Gallaey了解です！
よろしくお願いします🙇‍♂️
